require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.6

  Exclude:
    - 'db/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'spec/**/*'
    - 'bin/**/*'
    - 'config/**/*.rb'
    - 'features/**/*.rb'
    - 'lib/**/*.rake'
    - 'vendor/**/*'

Documentation:
  # Skips checking to make sure top level modules / classes have a comment.
  Enabled: false

Style/ClassAndModuleChildren:
  # Skips checking the style of children definitions at classes and modules.
  #
  # Basically there are two different styles:
  #
  # `nested` - have each child on a separate line
  #   class Foo
  #     class Bar
  #     end
  #   end
  #
  # `compact` - combine definitions as much as possible
  #   class Foo::Bar
  #   end
  #
  # With it disabled, either or is valid.
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/ClassLength:
  Max: 250

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 45

Layout/HashAlignment:
  EnforcedColonStyle: table

Style/Lambda:
  Enabled: false
